import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });
import ErrorBoundary from "./ErrorBoundary";
import { ContextProviders } from "./ContextProviders";
import { error } from "console";
export const metadata: Metadata = {
  title: "TEST-APP",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ErrorBoundary>
      <html lang="en">
        <body className={inter.className}>
          <ContextProviders>{children} </ContextProviders>
        </body>
      </html>
    </ErrorBoundary>
  );
}
